// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Ui-0nWtYXCxiYh16zwo8smAKXvPcPf0',
    appId: '1:583700667869:android:81d199c2d8874acf9b6a34',
    messagingSenderId: '583700667869',
    projectId: 'chat-app-c1792',
    storageBucket: 'chat-app-c1792.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPqZeaj-rHXFVzUFurEc75HeCoynp_dNk',
    appId: '1:583700667869:ios:b4a22d04bca3a2619b6a34',
    messagingSenderId: '583700667869',
    projectId: 'chat-app-c1792',
    storageBucket: 'chat-app-c1792.firebasestorage.app',
    androidClientId: '583700667869-grh90vtaf75vgiq9cht0kqo6lac1d7gp.apps.googleusercontent.com',
    iosClientId: '583700667869-sonjthce4ihlill24a77qmfqjtv0hita.apps.googleusercontent.com',
    iosBundleId: 'com.example.interntest',
  );
}
